### ISSUE TITLE
请问如何启用mermaid

### ISSUE THREAD

**Issue by spldmanager** [hexo-theme-Acrylic/Hexo-Theme-Acrylic#70]
我看_config.yml中有

```
# 标签外挂 (mermaid)
mermaid:
  enable: true
  # 主题: default/forest/dark/neutral
  theme:
    light: default
    dark: dark
```
设置enable为true也不起作用

```
    mermaid: https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
```
这边设置了cdn，也没有去请求
请问如何开启呢，而且不仅仅只是mermaid，好多公式等插件估计都要类似的开启，现在就是不知道要怎么做
